version: 2

updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: '06:00'
      timezone: Asia/Tehran
    open-pull-requests-limit: 10
    groups:
      production-dependencies:
        dependency-type: production
        update-types:
          - minor
          - patch
      development-dependencies:
        dependency-type: development
        update-types:
          - minor
          - patch

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: '06:15'
      timezone: Asia/Tehran
    groups:
      github-actions:
        patterns:
          - '*'

  - package-ecosystem: docker
    directory: /infra/docker
    schedule:
      interval: weekly
      day: monday
      time: '06:30'
      timezone: Asia/Tehran
    groups:
      docker-images:
        patterns:
          - '*'
